sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "U5pANP5iY/nCS4xwWAQW5r9Q8On6btU1rpxpT9wyGykTbELB5NjtQ3YUmKjndH2jRH14YoaWDNu00MW1ZojykKwUqLwRVpKLuw4AivlkTSTe6iF/kO1TcS5B5BOUbQ2IFcDVVMNNL4C1Vn855nHz4zDCvgFYZcZcL/naaMEn4nencS5ufZ6skCTFp87//GIi4QObBoJv6IfY3Ec2tfNIO0AFh+o2+0TX7+rruu1DsZZpeOCfMsz1O3OR3dKvms3QSIbcFWK3kKk2yNQHTuBRAUKLmMQ15O+J83byynFmhD2omKHgvZjma4I+qoC4W0S+KuPGj7wLrgcctQCp00u8Oag1nP/OATo/zwfiJVj0FMUIb/RPFzybzx+5KeGozwHlzWOXKhyO+hXFIWe/ulXFEw9EZTJCtuL5VHZaRsJ065cxloURsLss2/41JLnx5ZPDRmZ5YeUwqurNIrEYRElWNOWvofFy2svC3XdiO8wRXOKuf+ATCslunNKbrLEY9Tf8Cil82T1YnZ//j2xVhIxa5rEr6HHxbKnRCsDGoLe3yemWntpIYb7cC4fv676QdTaOZ96yxnbOlHmbdXeLD89s+WelEfZtLc4O6OnEHCJi6pd2sPXW+Wvs2iAxcPOrsetZvSdVmZPBCx35L18BAI6pHLGBU7cJGJSfEF7N1vV+kKk="
branches:
  only:
    - master
